PACKAGE_NAME = "raglite-toolkit"
PACKAGE_VERSION = "0.1.0"

SUPPORTED_EXTENSIONS = {".pdf", ".txt", ".json", ".md", ".markdown", ".docx"}

DEFAULT_CHUNK_SIZE = 500
DEFAULT_CHUNK_OVERLAP = 50

DEFAULT_TOP_K = 5
DEFAULT_SCORE_THRESHOLD = 0.0

DEFAULT_TEMPERATURE = 0.0

DEFAULT_STORE_DIRNAME = ".raglite"
DEFAULT_COLLECTION_NAME = "default"

DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 8085
